### PR TITLE
script usage readme

### PR DESCRIPTION
**Pull request by Praneet9**
Added steps to setup development and production environment for Pufferfish Software
Also includes steps to clone and flash SD Card.

### CODE REVIEW

**Comment by ethanjli** [comment]
Looks great to me! For records-keeping:

1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too?
2. Were any of these contributions also part of work you did for an employer or a client?
3. Does this work include, or is it based on, any third-party work which you did not create?

**Comment by Praneet9** [comment]
1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? **Yes**
2. Were any of these contributions also part of work you did for an employer or a client? **No**
3. Does this work include, or is it based on, any third-party work which you did not create? **No**

**Review by ethanjli — APPROVED** [review]

**Comment by ethanjli** [comment]
Can you see if the firmware checks get resolved after you merge the develop branch into this branch?

**Comment by Praneet9** [comment]
> Can you see if the firmware checks get resolved after you merge the develop branch into this branch?

Merging develop seems to have solved the problem.

**Pull request merged**
