### PR TITLE
Add unit test cases for the SFM3019 high-level driver

### PR DESCRIPTION
**Pull request by raavilagoo**
This pull request covers high-level driver tests for SFM3019.
Summary of changes made in this PR
1. output method added in StateMachine class  
2. get_state method added in Sensor class
3. InitializableState prev_state_ added in setup and output method 
4. retry_count renamed to fault_count

This does not include following test cases, to be covered in next pull request.
1. Test cases related to delay function - delay function is not implemented yet.
2. I2CDeviceStatus to be updated in read and write method, currently its defined to I2CDeviceStatus::ok in I2CDevice.
3. Test cases for I2CDevice's read method for different I2CDeviStatus other than ok.
4. Test cases for I2CDevice's write method for different I2CDeviStatus other than ok.
5. Partial fixes for buffer sizes in mock I2CDevice, permanent solution would be to replace array to vector.

### CODE REVIEW

**Comment by raavilagoo** [comment]
Hi @ethanjli 
Scenario - In output method, measure method should return failed state.
 4 wrong read buffer for read_sample in measure method, In this case every time retry_count increments from 0 to 1.
if(retry_count_ > max_retries_measure) this condition never arises( max_retries_measure = 8 ), hence measure never returns failed.
Same logic is implemented in case of check-range method.

**Comment by raavilagoo** [comment]
@ethanjli 
Pull request is ready for review 
https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-678d5710ff250bc699e236d453756e523b05e23e98bd14dc3637a71a791e0dd4R176

https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-3a356ad59e377671abb149aa083f4cd1af87c97f981c0479223c2f358353c8b0R34

https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-678d5710ff250bc699e236d453756e523b05e23e98bd14dc3637a71a791e0dd4R283

**Comment by raavilagoo** [comment]
@ethanjli 
https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-bffa039ecb6c121ac2f2f3ccad3a74c8fd33852e2a8107d3582f2722976ba75eR213

I would like to discuss this on our call.

**Comment by raavilagoo** [comment]
@ethanjli This is pull request is ready for review.

https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-678d5710ff250bc699e236d453756e523b05e23e98bd14dc3637a71a791e0dd4R308

https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-3a356ad59e377671abb149aa083f4cd1af87c97f981c0479223c2f358353c8b0R54

https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-678d5710ff250bc699e236d453756e523b05e23e98bd14dc3637a71a791e0dd4R152

**Comment by ethanjli** [comment]
I tested out the firmware on this PR with the Nucleo board and confirmed that:

1. under normal conditions with the SFM3019 sensor plugged in and working, the setup code successfully completes
2. under normal conditions with the SFM3019 sensor *not* plugged in, the setup code successfully reports a failure

In addition to the changes to the behavior specification (.txt) files we discussed yesterday, this PR also needs some text in its Description field explaining the scope of this PR and what major categories of tests are left for future PRs (e.g. the changes we discussed we'll need to make to the I2C mock device, and tests which are left out of this PR because they require those changes).

**Comment by raavilagoo** [comment]
@ethanjli This PR is ready for review
https://github.com/pez-globo/pufferfish-software/pull/444/files#diff-678d5710ff250bc699e236d453756e523b05e23e98bd14dc3637a71a791e0dd4R294

**Comment by raavilagoo** [comment]
This PR  passes clang-tidy and clang-format checks.
Some changes required in I2CDevice file will be included in next PR. 
 I will merge in this PR now.


For records-keeping:

This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? - Yes
Were any of these contributions also part of work you did for an employer or a client? - No
Does this work include, or is it based on, any third-party work which you did not create? - No

**Pull request merged**
