### PR TITLE
Hotfix for Eslint & unit test

### PR DESCRIPTION
**Pull request by Sudhir-dev**
This PR consists

* Eslint fix unused variables error fixing
* Moving unit test directory "spec" outside "src" directory

### CODE REVIEW

**Comment by Sudhir-dev** [comment]
1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? **Yes**
2. Were any of these contributions also part of work you did for an employer or a client? **No**
3. Does this work include, or is it based on, any third-party work which you did not create? **No**

**Comment by ethanjli** [comment]
Looks good (I squashed and merged a PR into develop which causes a merge conflict here though). Does `yarn lint` need to be reconfigured to also lint files in the `spec` directory?

Also, is there any way we can rename the `spec` directory to `tests`, for consistency with the naming scheme in the backend and firmware?

**Comment by Sudhir-dev** [comment]
* Renamed the spec directory to tests
* Configured Linting files in the tests directory

**Review by ethanjli — APPROVED** [review]
I tried it out and it works fine for me.

**Pull request merged**
