### PR TITLE
Add dependencies and config for auto documentation.

### PR DESCRIPTION
**Pull request by Tanmay06**
Modified poetry project and lock files to install sphinx dependencies. Also modified README.md with directions to generate documentations. There are still some changes to be done to capture package level docstrings.

### CODE REVIEW

**Comment by ethanjli** [comment]
Should we try to finish this PR by just merging in what we have now and creating a future Github Issues item to look into using a Makefile to simplify building the docs, or would you prefer to just close this PR without merging?

**Comment by Tanmay06** [comment]
I'm almost done making a MAKEFILE for this PR. I believe we can close this today.

**Comment by Tanmay06** [comment]
I think this is ready now. One note, the module starting with `_`, like `_trio.py`, is ignored by the auto-module plugin. In future we need to find a way overcome or rename the modules.

**Comment by Tanmay06** [comment]
Sphinx auto-documentation requires `python3-sphinx` to be present in the system. It can be done using `apt-get install python3-sphinx`. But since it is a dev dependency rather than production, I'm not sure whether it should be added to the deployment process or not. I guess @Praneet9 can suggest a better solution for this.

**Comment by Praneet9** [comment]
> Sphinx auto-documentation requires `python3-sphinx` to be present in the system. It can be done using `apt-get install python3-sphinx`. But since it is a dev dependency rather than production, I'm not sure whether it should be added to the deployment process or not. I guess @Praneet9 can suggest a better solution for this.

We have a development environment setup.
As this is a dev env requirement we can add this to poetry installation script as it already installs all other packages.
Another way of doing it would be to just add it to setup.sh which does the development environment setup.

**Comment by Tanmay06** [comment]
Another possible way that I see could be to just add the installation step in `backend/docs/README.md`. Since this not a necessary dependency for development it could be skipped from deployment process and explicitly installed whenever the need arises.

**Comment by Tanmay06** [comment]
I not sure why but `pylint` has started throwing this `raise-missing-from` warnings during the checks. This happened a couple of times before on my local machine but some how it got magically resolved.

**Comment by ethanjli** [comment]
The docs build works for me. Can you see if the instructions provided at https://stackoverflow.com/a/63852262 will solve the pylint complaints?

Before you merge, can you add/modify a `.gitignore` to remove any auto-generated build files?

For records-keeping:

1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too?
2. Were any of these contributions also part of work you did for an employer or a client?
3. Does this work include, or is it based on, any third-party work which you did not create?

**Comment by Tanmay06** [comment]
For records-keeping:

1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? **Yes**
2. Were any of these contributions also part of work you did for an employer or a client? **No**
3. Does this work include, or is it based on, any third-party work which you did not create? **No**

**Comment by Tanmay06** [comment]
I have made the necessary changes to the branch and also fixed the `pylint` warnings.

**Review by ethanjli — APPROVED** [review]

**Pull request merged**
