### PR TITLE
Change event type button style in events log

### LINKED ISSUE #427: Visually differentiate active alarms in the Events Log view
Currently, the events log view shows all active alarms the same way as regular log events. This makes it almost impossible to identify the sequence of events leading up to an alarm, and to understand the context around active alarms. We should have change the visual presentation of active alarms to make them easy to see among regular log events. It would be a good idea to not rely solely on color to mark active alarms. For example, maybe each row corresponding to an active alarm, we could encapsulate the alarm label of the "Event" column in a red rounded rectangle - this would establish a visual link to the red rounded rectangle in the topbar, to communicate that that row corresponds to an active alarm.

### PR DESCRIPTION
**Pull request by rohanpurohit**
This fixes #427

### CODE REVIEW

**Comment by rohanpurohit** [comment]
Few issues I see from testing:
- `AlarmLimits` events and `control (Ventilation etc)` had color as `${theme.palette.primary.main}` which is the blue color we have everywhere on frontend, it looks good when the button is `filled`, but is not quite `visible` after this PR, which is just a border.
1. we could maybe increase border size from `1px` to `2/4px`
2. we could change the color (to green or something that's clearly visible)

**Comment by ethanjli** [comment]
Yes, let's increase the border so it looks thick. 4px would be ideal, unless it interferes with the text or makes the fill region look too thin

**Comment by rohanpurohit** [comment]
> Yes, let's increase the border so it looks thick. 4px would be ideal, unless it interferes with the text or makes the fill region look too thin

I personally like how `4px` looks

**Comment by ethanjli** [comment]
It looks good on the Raspberry Pi with the touchscreen display. I noticed that you've reduced the number of rows per page from 9 to 8, which is fine. Ideally we would have 10 rows per page since that's a nice round number, but since we already weren't at 10 rows per page, I wouldn't consider it a regression of this PR. A future visual improvement might be to adjust padding and margins for the event type button, since they're quite tall now that we've added 8 px of height to each one, but that might make things look visually cramped; a future solution might be to play around more with the styling in other ways so that we can make the things under the "Type" column less tall. I think this PR is fine to merge as it is right now.

For records-keeping:
1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too?
2. Were any of these contributions also part of work you did for an employer or a client?
3. Does this work include, or is it based on, any third-party work which you did not create?

**Comment by rohanpurohit** [comment]
1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? Yes.
2. Were any of these contributions also part of work you did for an employer or a client? No.
3. Does this work include, or is it based on, any third-party work which you did not create? No.

**Review by ethanjli — APPROVED** [review]

**Pull request merged**
