### PR TITLE
New Designs - Dashboard & Sidebar

### PR DESCRIPTION
**Pull request by Sudhir-dev**
This PR includes 

* Sidebar with new Design
* Dashboard page design

This PR does does not include
* New Sidebar - Close & Lock Screen Icon (Need to be provided by UI/UX team)
* New Sidebar - Home button navigation (Not sure which page to be navigated)

### CODE REVIEW

**Comment by ethanjli** [comment]
This generally looks good to me. A few things I've noticed which need to be changed in either this PR or a future PR:

- The "More Values" and "More Controls" buttons should be removed from the HFNC layout.
- The Controls toolbar is divided into four areas, two of which are FiO2 and Flow Rate, and two of which are blank areas. Instead, it should only be divided into two areas.
- The "Modes", "Set Alarms", "All Values", and "Settings" screens during active ventilation should have the same sidebar as the dashboard - currently they have the same sidebar as the "Quick Start" screen during standby. I believe the set of screens accessible from the sidebar during active ventilation will be changing anyways - so I'll let you decide whether to fix the sidebar for those screens now or later.
- The Home button in the sidebar from the dashboard should have the same effect as the "hide sidebar" button.
- The "More Waveforms" button from the dashboard appears to be layered on top of everything else, including the Lock Screen overlay and the sidebar overlay.

**Comment by Sudhir-dev** [comment]
Have fixed issues mentioned except for 

"The Home button in the sidebar from the dashboard should have the same effect as the "hide sidebar" button."

Once the sidebar layout is changed according to Standby/Ventilating state, Home button could be used to navigate "Dashboard" page

**Comment by Sudhir-dev** [comment]
1. This project is licensed under Apache License v2.0 for any software, and Solderpad Hardware License v2.1 for any hardware - do you agree that your contributions to this project will be under these licenses, too? **Yes**
2. Were any of these contributions also part of work you did for an employer or a client? **No**
3. Does this work include, or is it based on, any third-party work which you did not create? **No**

**Comment by Sumitzways** [comment]
Improvement Required:- 

- On set alarm page after clicking on Apply changes button we should have "Successfully change Message /Pop-up"  or else redirect it on home page.  Same for Settings page.  Settings -> Display.
 
-Disable the mode expect HFNC for now because by mistake if user select other mode then waveforms getting freeze.

**Review by ethanjli — APPROVED** [review]

**Comment by ethanjli** [comment]
Another small last-minute change (either for this PR or a future PR): the "Main view" menu button should be removed from the top bar, as it is no longer needed.

**Pull request merged**
